apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
  labels:
    app: store-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: siamchamnankit/store-service:eks-egat-260305
          imagePullPolicy: Always
          env:
            - name: BANK_GATEWAY
              value: thirdparty-service:8882
            - name: SHIPPING_GATEWAY
              value: thirdparty-service:8883
            - name: POINT_GATEWAY
              value: point-service
            - name: STORE_WEB_HOST
              value: http://a0d66da3269b342eeac0719b3194fad0-f7f38988794c33da.elb.ap-southeast-7.amazonaws.com
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-connection
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: ac8a0688b9ef54de99cb38abcfd35beb-04cd7576ff4c204e.elb.ap-southeast-7.amazonaws.com:4317
            - name: INSECURE_MODE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: store-service
            - name: PYROSCOPE_URL
              value: "http://43.209.161.156:4040"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: ClusterIP
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
