apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
  labels:
    app: store-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: siamchamnankit/store-service:latest
          env:
            - name: BANK_GATEWAY
              value: thirdparty-service:8882
            - name: SHIPPING_GATEWAY
              value: thirdparty-service:8883
            - name: POINT_GATEWAY
              value: point-service
            - name: STORE_WEB_HOST
              value: http://sck-dojo.ddns.net
            - name: DB_CONNECTION
              value: user:password@(mysql:3306)/store
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: ClusterIP
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
