apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
  labels:
    app: store-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
      - name: store-service
        image: srank123/store-service
        env:
        - name: BANK_GATEWAY
          value: host.docker.internal:8884
        - name: SHIPPING_GATEWAY
          value: host.docker.internal:8885
        - name: POINT_GATEWAY
          value: point-service-svc:8001
        - name: STORE_WEB_HOST
          value: http://host.docker.internal
        - name: DB_CONNECTION
          value: user:password@(host.docker.internal:3308)/store
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api/v1/product
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/v1/product
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: ClusterIP
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000