apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-endpoints
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://REPLACE_OTEL_ENDPOINT:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  PYROSCOPE_URL: "http://REPLACE_PYROSCOPE_ENDPOINT:4040"
