apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-web-deployment
  labels:
    app: store-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: store-web
    spec:
      containers:
      - name: store-web
        image: srank123/store-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: store-web
spec:
  type: ClusterIP
  selector:
    app: store-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000