apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-service-deployment
  labels:
    app: point-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: point-service
    spec:
      containers:
        - name: point-service
          image: siamchamnankit/point-service:latest
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://ac8a0688b9ef54de99cb38abcfd35beb-04cd7576ff4c204e.elb.ap-southeast-7.amazonaws.com:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: point-service
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /api/v1/point
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/v1/point
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: point-service
spec:
  type: ClusterIP
  selector:
    app: point-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
